server:
  port: 8500
spring:
  application:
    name: poh-server
  # 数据库配置
  datasource:
    druid:
      url: jdbc:mysql://服务器IP:端口/poh_db?&useSSL=false&serverTimezone=GMT&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: 用户名
      password: 密码
      max-active: 500
      max-wait: 200
      min-idle: 20
  # redis配置
  redis:
    host: 服务器IP
    port: redis端口
  # 消息中间件配置
  rabbitmq:
    host: 服务器IP
    port: rabbitmq端口
    username: poh_admin
    password: rabbitmq密码
    virtual-host: /poh
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  secret-key: poh-location*&$!#
  expiration: 86400000

security:
  ignore-address:
    - /css/**
    - /js/**
    - /images/**
    - /**/*.html
    - /logout   # 注：这个 /logout 应该放在下方允许访问的地址中，但是放到下面这个地址依然会被拦截，所以放在上面处理
    - /equipment/location/**
  permit-address:
    - /
    - /login
    - /register
    - /checkUser/**